// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIce6kYS3DUwTsg3lhqZh2_rP0Z--IylA',
    appId: '1:670226121606:web:da7fb076cc1a825a852207',
    messagingSenderId: '670226121606',
    projectId: 'phone-authentication-6d501',
    authDomain: 'phone-authentication-6d501.firebaseapp.com',
    storageBucket: 'phone-authentication-6d501.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORC19aqfXqyaWR3MRQGUJVm2mv_FN2eQ',
    appId: '1:670226121606:android:213e47bc423326ed852207',
    messagingSenderId: '670226121606',
    projectId: 'phone-authentication-6d501',
    storageBucket: 'phone-authentication-6d501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZv6qci4dBDBbzhm7ltgDbCkuWWMgq0PY',
    appId: '1:670226121606:ios:5aaa44363e65c2cb852207',
    messagingSenderId: '670226121606',
    projectId: 'phone-authentication-6d501',
    storageBucket: 'phone-authentication-6d501.appspot.com',
    iosClientId: '670226121606-8f002srkkp6361gd6uhpgele4bbi9p8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZv6qci4dBDBbzhm7ltgDbCkuWWMgq0PY',
    appId: '1:670226121606:ios:5aaa44363e65c2cb852207',
    messagingSenderId: '670226121606',
    projectId: 'phone-authentication-6d501',
    storageBucket: 'phone-authentication-6d501.appspot.com',
    iosClientId: '670226121606-8f002srkkp6361gd6uhpgele4bbi9p8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );
}
